### ISSUE TITLE
Bug in visualization when `r_icb=0`

### ISSUE THREAD

**Issue by AnkitBarik** [repepo/kore#14]
When `r_icb=0`, visualizing the spinover mode works with `plot_fields.py` but not with `koreviz`. There is a bug in there somewhere, needs to be debugged.

**Comment by fleursys** [comment]
It's a problem with specifiying n and n0, I remember dealing with this at one point, so it should be in the MAC waves branch.

**Comment by fleursys** [comment]
pushed it!
