### ISSUE TITLE
libration forcing

### ISSUE THREAD

**Issue by repepo** [repepo/kore#6]
- For sake of simplicity the longitudinal libration forcing in assemble.py (forcing==7) should contain just the longitudinal libration part, i.e. the m=0 part, without any reference to any m=2 forcing. As it is now it duplicates the more generic m=2 radial velocity forcing (forcing==9) already existing.

- To simulate a tidally deformed boundary undergoing libration (m=2) the user should use the forcing==9 option instead. It should be up to the user to choose the appropriate amplitude and frequency.  

- The name "axial forcing (m=0)" is ambiguous (is the forcing along the axis??) it is more descriptive 'azimuthal' or 'longitudinal'.

**Comment by fleursys** [comment]
Changed the name of the first part in forcing==7 to "azimuthal boundary forcing" and deleted the second part.
